name = "GameHoppingInLean"
version = "0.1.0"
keywords = ["math"]
defaultTargets = ["GameHoppingInLean"]

[leanOptions]
pp.unicode.fun = true # pretty-prints `fun a ↦ b`
relaxedAutoImplicit = false
weak.linter.mathlibStandardSet = true
maxSynthPendingDepth = 3

[[require]]
name = "mathlib"
scope = "leanprover-community"
rev = "86d0bf37418c1b2448cbd82bc71c28a3fc6528c6"

[[lean_lib]]
name = "GameHoppingInLean"
