name = "GameHoppingInLean"
version = "0.1.0"
keywords = ["math"]
defaultTargets = ["GameHoppingInLean"]

[leanOptions]
pp.unicode.fun = true # pretty-prints `fun a ↦ b`
relaxedAutoImplicit = false
weak.linter.mathlibStandardSet = true
maxSynthPendingDepth = 3
# TODO: remove
linter.unusedSimpArgs = false
weak.linter.style.longLine = false
weak.linter.flexible = false
weak.linter.style.header  = false


[[require]]
name = "mathlib"
scope = "leanprover-community"
rev = "8f9d9cff6bd728b17a24e163c9402775d9e6a365"

[[require]]
name = "VCVio"
scope = "Verified-zkEVM"
rev = "e7f4c"


[[lean_lib]]
name = "GameHoppingInLean"
